# Generated by Django 4.1.1 on 2022-10-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('url', models.URLField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
